name: Build and Test Orbit

on:
  push:
    branches: [ "main" ] 
  pull_request:
    branches: [ "main" ] 

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  build-backend:
    runs-on: ubuntu-latest

    steps:

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2  

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'     

      - name: Build and test with Maven
        run: mvn -B package --file pom.xml

      - name: Upload backend artifact
        uses: actions/upload-artifact@v4
        with:
          name: orbit-backend
          path: target/*.jar

